### ISSUE TITLE
Add DC.gov Google Analytics code

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#1]
- add DC.gov GA code
- remove current GA code

**Comment by krusynth** [comment]
Should this be the main dc.gov code (`UA-2638726-1`) or is there a different one for this site you'll want to use?

**Comment by cmgiven** [comment]
It should be the main code. All dc.gov sites feed into that single property.

**Comment by krusynth** [comment]
:+1:

**Comment by cmbirk** [comment]
This has been installed.  @cmgiven @mattbailey0 can one of you confirm you're seeing the data coming through?

**Comment by cmgiven** [comment]
As of the moment, we do not see any traffic from drafts.dc.gov. Looking at today.

**Comment by cmbirk** [comment]
Are you able to grant me temporary access to the account to debug?

**Comment by cmgiven** [comment]
I was just rechecking this, and I can confirm it's now working.
