### ISSUE TITLE
new default photo for featured document

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#11]
The current default photo is of the capitol building - not ideal for a site about city government.  We'll want to update this to something DC-specific.

**Comment by mattbailey0** [comment]
Maybe? https://commons.wikimedia.org/wiki/File:The_Wilson_Building.jpg

**Comment by mattbailey0** [comment]
The concept I was going for was something along the lines of a blueprint or "draft" version of the Wilson building.  This was the best I could readily find.

**Comment by mattbailey0** [comment]
The flag might also be good - https://en.wikipedia.org/wiki/Flag_of_the_District_of_Columbia#/media/File:Flag_of_Washington,_D.C..svg

**Comment by cmgiven** [comment]
I'm stumped here. Here's a terrible instagram-y photo where the sky kinda matches the primary color.

![wilson-stylized](https://cloud.githubusercontent.com/assets/5375557/12238804/d4b1adb0-b853-11e5-96ba-216e92618792.jpg)

**Comment by mattbailey0** [comment]
Let's just use the DC flag if that works with the design plausibly
