### ISSUE TITLE
figure out a strategy for copyright, privacy, and terms of use policies

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#13]
Current links in the sitewide footer are, reasonably enough, to the OpenGov Foundation's content on these topics.  We need to figure out how to resolve these with DC Gov's equivalents. I took a gander at them and don't see huge inconsistencies.  I don't think this needs to be solved for launch.

**Comment by krusynth** [comment]
All of our docs on these topic are [open and CC0](https://github.com/opengovfoundation/site-policy) so if you all want to fork or contribute to ours, that's great!

**Comment by emanuelfeld** [comment]
@krues8dr the "Opt-In" section of the terms and conditions does not apply to this instance, does it?

**Comment by emanuelfeld** [comment]
I'm going to close this and split it up into multiple issues, because the three seem relatively discrete.
