### ISSUE TITLE
Update /about content

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#15]
/about needs to be updated for its new context as part of dc.gov

**Comment by mattbailey0** [comment]
Draft content is available at https://dcds.hackpad.com/Madison-thoughts-and-content-JVGATurVVdw - @krues8dr you will want to read through it to see if it's OK by you!

**Comment by krusynth** [comment]
@mattbailey0 @cmgiven I'm linkifying the about text - is there an official page for `the OCTO Technology Innovation Program` or should I link to the OCTO page here?

**Comment by krusynth** [comment]
Also, `Stay connected by signing up for email updates.`  is there an address to do this?  We've removed the subscribe link from the header, but I can add a new one here.

**Comment by cmgiven** [comment]
"OCTO Technology Innovation Program": Let's use `mailto:digitalservice@dc.gov`

Let's cut "Stay connected by signing up for email updates."

**Comment by cmgiven** [comment]
(I'll note the first one's a stopgap. The page doesn't exist yet, but it will soon.)
