### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by cmgiven** [DCgov/dc-madison#24]
I'm getting a 500 response when I attempt to:
- Reset my password
- Update my profile

**Comment by krusynth** [comment]
I can reproduce for password reset, but not profile update - what fields are you editing, specifically?

**Comment by cmgiven** [comment]
Sorry, the specific action was to click the verify button.

Chris

On January 11, 2016 at 4:14:04 PM, Bill Hunt (notifications@github.commailto:notifications@github.com) wrote:

I can reproduce for password reset, but not profile update - what fields are you editing, specifically?

**Comment by cmgiven** [comment]
Here's another error, encountered while attempting to add a new document (on the second screen).

```
Error: [$injector:unpr] http://errors.angularjs.org/1.2.28/$injector/unpr?p0=%24uibModalProvider%20%3C-%20%24uibModal%20%3C-%20modalService
    at Error (native)
    at https://drafts.dc.gov/build/angular.js?6e3dee64:1:450
    at https://drafts.dc.gov/build/angular.js?6e3dee64:1:15441
    at Object.c [as get] (https://drafts.dc.gov/build/angular.js?6e3dee64:1:14512)
    at https://drafts.dc.gov/build/angular.js?6e3dee64:1:15515
    at c (https://drafts.dc.gov/build/angular.js?6e3dee64:1:14512)
    at d (https://drafts.dc.gov/build/angular.js?6e3dee64:1:14727)
    at Object.instantiate (https://drafts.dc.gov/build/angular.js?6e3dee64:1:14893)
    at Object.<anonymous> (https://drafts.dc.gov/build/angular.js?6e3dee64:1:15156)
    at Object.d [as invoke] (https://drafts.dc.gov/build/angular.js?6e3dee64:1:14757) <div ui-view="" class="ng-scope">(anonymous function) @ angular.js:87
```

**Comment by krusynth** [comment]
That's an unrelated issue, I'll open a separate ticket for it.

**Comment by cmbirk** [comment]
It appears that requesting validation makes duplicate requests.  I'm getting an integrity constraint error.

```

'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '176-verify' for key 'user_meta_user_id_meta_key_unique' (SQL: insert into `user_meta` (`meta_key`, `meta_value`, `user_id`, `updated_at`, `created_at`) values (verify, pending, 176, 2016-01-11 22:23:04, 2016-01-11 22:23:04))' in .../vendor/laravel/framework/src/Illuminate/Database/Connection.php:651

```

**Comment by krusynth** [comment]
Password reset is fixed.

**Comment by krusynth** [comment]
Create a document is fixed.

**Comment by krusynth** [comment]
Request validation is fixed.  Thanks for catching these @cmgiven !  It looks like our upgrade & merge did not go as smoothly as we'd hoped, but I think we're getting down to the last few issues here.
