### ISSUE TITLE
Angular not loaded on doc page

### ISSUE THREAD

**Issue by cmgiven** [DCgov/dc-madison#25]
It was working at some point. But no longer. Have tried reverting the document to how it was when it worked, but that doesn't seem to have done anything.

https://drafts.dc.gov/docs/draft-open-data-policy

**Comment by krusynth** [comment]
Just down for a second while I redeploy, no worries. :)  All better now.

**Comment by cmgiven** [comment]
Fantastic!

:beer:

**Comment by krusynth** [comment]
@cmgiven @mattbailey0 just a heads-up: I'm heading to dinner, but will be back online in an hour for anything new you all find.
