### ISSUE TITLE
update palette to match dc.gov

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#3]
as a first step on look and feel, let's update the core css palette to bring the blues and reds, etc, in line with DC.gov.  I'll supply hex values and more detail shortly.

**Comment by mattbailey0** [comment]
For launch, this may be as simple as swapping out the #4a4f51 in the header and footer (globally?) for the blue that DC.gov uses - #2B4888

**Comment by krusynth** [comment]
I found the [OCTO web guide](http://octo.dc.gov/node/706822) but it doesn't have a lot of useful info for us I think.

**Comment by krusynth** [comment]
![screen shot 2016-01-11 at 11 52 36 am](https://cloud.githubusercontent.com/assets/127904/12240100/d7157838-b859-11e5-933b-4b9caefa5e88.jpg)

Those blues kinda clash, what do you think @mattbailey0

**Comment by krusynth** [comment]
I propose replacing the existing blue with just the DC blue.  Switching around the headers is an improvement as well:

![screen shot 2016-01-11 at 12 03 17 pm](https://cloud.githubusercontent.com/assets/127904/12240431/621b8354-b85b-11e5-88a1-974b97fb8b60.jpg)

**Comment by krusynth** [comment]
Implementing this for now, we can revise as needed.

**Comment by krusynth** [comment]
Please reopen if this won't do.

**Comment by cmgiven** [comment]
Looks great!
