### ISSUE TITLE
Redirect dc.mymadison.io to drafts.dc.gov

### ISSUE THREAD

**Issue by krusynth** [DCgov/dc-madison#30]

**Comment by cmgiven** [comment]
This should probably be a 301 redirect. Not a high priority.

**Comment by krusynth** [comment]
Are you not seeing a 301?  I've got 301 configured - you may see a 307 from `http://dc.mymadison.io` to `https://dc.mymadison.io` first though.

**Comment by cmgiven** [comment]
Oh, huh, I am now. Don't know what happened there. Thanks!
