### ISSUE TITLE
Form text is cut off (Firefox Mac v43)

### ISSUE THREAD

**Issue by cmgiven** [DCgov/dc-madison#31]
We have some users poking around the site, so will be adding some minor things. Here's one.

![](https://files.slack.com/files-tmb/T07K5UXAN-F0J8GN3RA-9f6ed5c28a/screen_shot_2016-01-12_at_9.03.20_am_1024.png)

**Comment by cmbirk** [comment]
This is an issue with the way FF deals with padding on input elements.

**Comment by cmbirk** [comment]
https://github.com/opengovfoundation/madison/issues/772
