### ISSUE TITLE
"Updated NaN years ago"

### ISSUE THREAD

**Issue by cmgiven** [DCgov/dc-madison#32]
When viewing the draft policy while logged out, the Bill Stats displays this error.

https://drafts.dc.gov/docs/draft-open-data-policy

**Comment by krusynth** [comment]
Please make sure to give us browser/os for all of these - this Works For Me. ;)

**Comment by cmgiven** [comment]
Make sure you're logged out. Tested in Safari and Firefox on Mac.

**Comment by krusynth** [comment]
Confirmed in Safari.  Oh, webkit.

**Comment by krusynth** [comment]
Fixed in 444deddebd0c7ce2b992ed571214110bf1858118
