### ISSUE TITLE
adjust text on all automated emails to match new org, context

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#4]
emails such as the account setup email need to be adjusted to indicate that they're coming from DC.gov, include appropriate URLs, etc.

**Comment by cmbirk** [comment]
@mattbailey0 All of the email templates are [here](https://github.com/DCgov/dc-madison/tree/master/resources/views/email) (https://github.com/DCgov/dc-madison/tree/master/resources/views/email).  Would you let us know what you want the content of those templates to be?
