### ISSUE TITLE
Annotation (or maybe collaborator) count appears in header

### ISSUE THREAD

**Issue by cmgiven** [DCgov/dc-madison#41]
Chrome

<img width="453" alt="screen shot 2016-01-12 at 9 49 21 am" src="https://cloud.githubusercontent.com/assets/5375557/12266594/f9bfd2b2-b911-11e5-87a6-2981221d305f.png">

**Comment by cmgiven** [comment]
https://drafts.dc.gov/docs/draft-open-data-policy

**Comment by krusynth** [comment]
Dupe of opengovfoundation/madison#573  - This is one of the more insidious issues we've still got open atm.

**Comment by cmgiven** [comment]
Not a high priority.
