### ISSUE TITLE
Alignment is off on mobile homepage

### ISSUE THREAD

**Issue by emanuelfeld** [DCgov/dc-madison#45]
Parts are shifted left and X mark overlaps text.
![img_0335](https://cloud.githubusercontent.com/assets/4269640/12270491/500cd6f8-b924-11e5-991f-636283c014a7.PNG)
![img_0334](https://cloud.githubusercontent.com/assets/4269640/12270494/524127a8-b924-11e5-9236-1108a308217c.PNG)

**Comment by krusynth** [comment]
Mobile has a _lot_ of issues, fwiw.  It's probably not worth opening them one-at-a-time right now, maybe [open a ticket on our master repo](http://github.com/opengovfoundation/madison/issues/new) to aggregate them?

**Comment by emanuelfeld** [comment]
Sounds good. Moving these to a single ticket.
