### ISSUE TITLE
Annotation artifact at top of page

### ISSUE THREAD

**Issue by emanuelfeld** [DCgov/dc-madison#52]
Seems to correspond to another document:
<img width="479" alt="screen shot 2016-01-13 at 9 57 24 am" src="https://cloud.githubusercontent.com/assets/4269640/12297651/230db02e-b9dc-11e5-91cd-e840c975b5e0.png">
![image](https://cloud.githubusercontent.com/assets/4269640/12297676/396c2ec2-b9dc-11e5-8464-7d21ea2ef2d1.png)

**Comment by krusynth** [comment]
Tracking this here: opengovfoundation/madison#654

**Comment by krusynth** [comment]
This should be resolved now.

**Comment by emanuelfeld** [comment]
:+1:
