### ISSUE TITLE
SSL set up

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/dc-madison#6]
Get cert issued and set up in production.

**Comment by cmgiven** [comment]
@krues8dr: Would it be possible to use [Let's Encrypt](https://letsencrypt.org) to obtain the cert? As we've already redirected the domain, we should have everything we need to use the [webroot plugin](https://letsencrypt.readthedocs.org/en/latest/using.html#webroot) for verification.

Thoughts?

**Comment by krusynth** [comment]
Yup, that's no problem - the only reason I didn't do this already is because I assumed you all would want ownership of your own certs.  But we promise not to do anything evil with it. :smiling_imp:

**Comment by cmgiven** [comment]
@mattbailey0: We talked about this quickly. Want a final :+1: from you, but this sounds great to me.

**Comment by krues8dr** [comment]
:+1:  No prob.

**Comment by cmgiven** [comment]
Word from Matt: "Go ahead and set it up." We may continue with the other process, but this will ensure that we have something in place for tomorrow.

**Comment by krusynth** [comment]
:+1: will do.

**Comment by cmbirk** [comment]
I got the cert installed through letsencrypt, but we're going to want to set up a process to renew that.  Letsencrypt certs expire after 90 days, but you can renew through the cli tool

**Comment by krusynth** [comment]
@cmgiven Do you all want HSTS as well?  @mattbailey0 said to ask you.

**Comment by cmgiven** [comment]
Yes please.

**Comment by krusynth** [comment]
Great, done thanks to @cmbirk.
